language: node_js
node_js:
  - "0.10"
before_install:
  - "sudo apt-get install libicu-dev prosody luarocks"
  - "sudo luarocks install luabitop"
  # Workaround for a permissions issue with Travis virtual machine images
  # that breaks Python's multiprocessing:
  # https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - sudo cp test/resources/prosody.cfg.lua /etc/prosody/prosody.cfg.lua
  - sudo service prosody stop
before_script:
  - npm install -g grunt-cli